name = "NumericalDataManipulation"
uuid = "a93c41aa-7d95-5a09-865e-e3e4278104d5"
authors = ["Dmitry Vlasov <dmitry.v.vlasov@gmail.com>"]
version = "0.1.0"

[deps]
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
URIParser = "30578b45-9adc-5946-b283-645ec420af67"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
